### ISSUE TITLE
Чё за баг

### ISSUE THREAD

**Issue by nm17** [crinny/2019-ncov#1]
```
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    wrapper = nCoV(
  File "/data/data/com.termux/files/home/2019-ncov/game.py", line 21, in __init__
    self.webview_url = response["items"][0]["webview_url"]
KeyError: 'webview_url'
```
Версия 1bd78c32514227b40bb6f530bfe75d0bcf92f2c3
Python 3.8.1

**Comment by crinny** [comment]
Попробуй получить токен VK Admin

**Comment by nm17** [comment]
@crinny получил, теперь другой баг:
```
$ python bot.py
https://ncov.w83.vkforms.ru?vk_access_token_settings=&vk_app_id=7301988&vk_are_notifications_enabled=0&vk_is_app_user=0&vk_is_favorite=0&vk_language=ru&vk_platform=&vk_ref=other&vk_user_id=[REDACTED]&sign=[REDACTED]

Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    ill = f"{Fore.RED}Болен{Style.RESET_ALL}"
NameError: name 'Style' is not defined
```
Пакеты:
```
colorama==0.4.3
requests==2.22.0
```

**Comment by crinny** [comment]
Прогони весь процесс установки заново

**Comment by nm17** [comment]
Все запустил в pipenv, все равно так же.
Мои пакеты:
```
colorama==0.4.3
requests==2.22.0
  - certifi [required: >=2017.4.17, installed: 2019.11.28]
  - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
  - idna [required: >=2.5,<2.9, installed: 2.8]
  - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.8]
```
Pipfile.lock
```
{
    "_meta": {
        "hash": {
            "sha256": "a0d128aa0e5239841174a450cde13726f0fcde9d3aa762c148cbb0186e7742fe"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:017c25db2a153ce562900032d5bc68e9f191e44e9a0f762f373977de9df1fbb3",
                "sha256:25b64c7da4cd7479594d035c08c2d809eb4aab3a26e5a990ea98cc450c320f1f"
            ],
            "version": "==2019.11.28"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "colorama": {
            "hashes": [
                "sha256:7d73d2a99753107a36ac6b455ee49046802e59d9d076ef8e47b61499fa29afff",
                "sha256:e96da0d330793e2cb9485e9ddfd918d456036c7149416295932478192f4436a1"
            ],
            "index": "pypi",
            "version": "==0.4.3"
        },
        "idna": {
            "hashes": [
                "sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407",
                "sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c"
            ],
            "version": "==2.8"
        },
        "requests": {
            "hashes": [
                "sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4",
                "sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31"
            ],
            "index": "pypi",
            "version": "==2.22.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:2f3db8b19923a873b3e5256dc9c2dedfa883e33d87c690d9c7913e1f40673cdc",
                "sha256:87716c2d2a7121198ebcb7ce7cccf6ce5e9ba539041cfbaeecfb641dc0bf6acc"
            ],
            "version": "==1.25.8"
        }
    },
    "develop": {}
}
```
Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
colorama = "*"
requests = "*"

[requires]
python_version = "3.8"
```

**Comment by crinny** [comment]
Удали папку 2019-ncov и полностью начни установку сначала

**Comment by nm17** [comment]
Теперь все ок :+1:
